import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'secondary-container': '#c6eccc',
        'surface-variant': '#e2e2e2',
        'on-tertiary-fixed-variant': '#574500',
        'on-primary-fixed-variant': '#00522a',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#00210e',
        'on-secondary-fixed-variant': '#2d4e37',
        'on-error': '#ffffff',
        'surface': '#f9f9f9',
        'secondary-fixed': '#c6eccc',
        'inverse-on-surface': '#f1f1f1',
        'tertiary-fixed-dim': '#e9c349',
        'on-surface-variant': '#3f4940',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00210e',
        'tertiary-container': '#cba72f',
        'surface-bright': '#f9f9f9',
        'on-primary-container': '#94f0af',
        'error': '#ba1a1a',
        'surface-container-low': '#f3f3f3',
        'secondary': '#45664d',
        'secondary-fixed-dim': '#abd0b1',
        'surface-container-highest': '#e2e2e2',
        'on-secondary-container': '#4a6c53',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#1a1c1c',
        'tertiary-fixed': '#ffe088',
        'background': '#f9f9f9',
        'on-secondary': '#ffffff',
        'on-error-container': '#93000a',
        'surface-tint': '#006d3a',
        'primary-fixed-dim': '#7eda9a',
        'primary-fixed': '#9af6b5',
        'on-tertiary-fixed': '#241a00',
        'outline-variant': '#becabd',
        'surface-container-high': '#e8e8e8',
        'primary-container': '#00703c',
        'inverse-primary': '#7eda9a',
        'on-tertiary-container': '#4e3d00',
        'surface-container': '#eeeeee',
        'on-background': '#1a1c1c',
        'inverse-surface': '#2f3131',
        'tertiary': '#735c00',
        'on-tertiary': '#ffffff',
        'primary': '#00552c',
        'outline': '#6f7a6f',
        'surface-dim': '#dadada',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Newsreader', 'serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
export default config
